server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbBanking