server:
  port: ${port:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbBanking
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: client
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: *