server: 
  port: ${port:0}
  error:
    whitelabel: 
      enabled: true
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8085/eureka/
  instance: 
    hostname: localhost
    instance-id: 
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring: 
  application: 
    name: gateway-service
  cloud: 
    gateway: 
      routes: 
        - id: client-service
          uri: lb://client-service
          predicates: 
            - Path=/api/clients/v1,/api/clients/v1/*,/api/clients/v1/{id},/api/clients/v1/VIP/{clientId},/api/clients/v1/MYPE/{clientId},/api/clients/v1/report/{clientId}/products
          filters: 
            - StripPrefix=3
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/active,/api/products/active/*,/api/products/active/{id},/api/products/active/client/{clientId},/api/products/active/consumecredit/{id},/api/products/active/paycredit/{id},/api/products/active/transfer/{originId},/api/products/active/report/commission/{productId},/api/products/active/report/movements/{productId},/api/products/active/report/creditcard/movements/{cardNumber}
            - Path=/api/products/debitcard/**,/api/products/pasive/report/**,/api/products/pasive/**,/api/products/pasive
          filters:
            - StripPrefix=2
        # - id: movement-service
        #   uri: lb://movement-service
        #   predicates: 
        #     - Path=
        #   filters: 
        #     - StripPrefix=2