server: 
  port: ${port:0}
  error:
    whitelabel: 
      enabled: true
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8085/eureka/
  instance: 
    hostname: localhost
    instance-id: 
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring: 
  application: 
    name: gateway-service
  cloud: 
    gateway: 
      routes: 
        - id: client-service
          uri: lb://client-service
          predicates: 
            - Path=/api/clients/v1*
          filters: 
            - StripPrefix=3